package  Daje::Generate;
use Mojo::Base -signatures;

use Daje::GenerateSQL;
use Daje::GenerateSchema;
use Daje::GeneratePerl;

has 'config_path';

# NAME
#
# Daje::Generate - It's new $module
#
# SYNOPSIS
# ========
#     use Daje::Generate;
#     Daje::Generate->(
#           config_path => $path_to_config_files
#     )->process();
#
#
# DESCRIPTION
# ===========
#
# Daje::Generate is a tool to geneerate scaffolding code
#
# based on configuration
#
# METHODS
# =======
#
# process
#
#  $self->process();
#
#
# LICENSE
# # =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
#
# janeskil1525 E<lt>janeskil1525@gmail.comE<gt>
#
#

our $VERSION = '0.10';

sub process ($self) {
    Daje::GenerateSQL->new(
        config_path => $self->config_path(),
    )->process();
    Daje::GenerateSchema->new(
        config_path => $self->config_path(),
    )->process();
    Daje::GeneratePerl->new(
        config_path => $self->config_path(),
    )->process();
}


1;



__END__



#################### pod generated by Pod::Autopod - keep this line to make pod updates possible ####################

=head1 NAME

 Daje::Generate


=head1 SYNOPSIS

    use Daje::Generate;
    Daje::Generate->(
          config_path => $path_to_config_files
    )->process();




=head1 DESCRIPTION

NAME

Daje::Generate - It's new $module


Daje::Generate is a tool to geneerate scaffolding code

based on configuration



=head1 REQUIRES

L<Daje::Generate> 

L<Daje::GeneratePerl> 

L<Daje::GenerateSchema> 

L<Daje::GenerateSQL> 

L<Mojo::Base> 


=head1 METHODS


process

 $self->process();


LICENSE
# =======

Copyright (C) janeskil1525.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

AUTHOR

janeskil1525 E<lt>janeskil1525@gmail.comE<gt>




=cut

