package class Daje::Generate::Tools::Datasections;
use Mojo::Base -strict;

use v5.40;
use Mojo::Loader qw {data_section};
use Daje::Generate::Templates::Sql;
use Daje::Generate::Templates::Perl;

# Data::Load::Datasection  - Load and keep data sections from named *.pm
#
# Synopsis
# =========
#
# use GenerateSQL::Tools::Datasections
#
# my $data = GenerateSQL::Tools::Datasections->new(
#
#       data_sections => ['c1','c2','c3'],
#
#       source => 'Class::Containing::Datasections
#
#   )->load_data_sections();
#
# METHODS
# =======
# Get one section of loaded data
#
# my $c1 = $data->get_data_section('c1');
#
# Add a section of data
#
# $data->set_data_section('new_section', 'section data');
#
# Set a new source
#
# $data->set_source('New::Source');
#
# Add a new section to load
#
# $data->add_data_section('test');
#
#
# LICENSE
# =======
# Generate::Tools::Datasections  (the distribution) is licensed under the same terms as Perl.
#
# AUTHOR
# ======
# Jan Eskilsson
#
# COPYRIGHT
# =========
# Copyright (C) 2024 Jan Eskilsson.
#

our $VERSION = '0.01';

    has 'data_sections';
    has 'data_sec';
    has 'source';

    # Load all data_sections
sub load_data_sections($self) {

    try {
        my @data_sec = split(',', $self->data_sections) ;
        my $length = scalar @data_sec;
        for(my $i = 0; $i < $length; $i++){
            my $section = $data_sec[$i];
            if (!exists($self->data_sec->{$section})) {
                my $sec = data_section($self->source, $section);
                $self->set_data_section($section, $sec);
            }
        }
    } catch ($e) {
        die ("Error loading templates: $e");
    };

    return 1;
}
# Get one section
sub get_data_section($self, $section) {
    return $self->data_sec->{$section};
}
# Set a section
sub set_data_section($self, $key, $templ) {
    $self->data_sec->{$key} = $templ;
}
# Set Source
sub set_source($self, $source_class) {
    $self->source = $source_class;
}
# Add a section to the data sections_array to be loaded
sub add_data_section($self, $section) {
    $self->data_sections .','. $section;
}
1;
__DATA__

@@ test1

This is a sample text used for testing

@@ test2

This is also a sample text used for testing

__END__
1;










#################### pod generated by Pod::Autopod - keep this line to make pod updates possible ####################

=head1 NAME

lib::Daje::Generate::Tools::Datasections - lib::Daje::Generate::Tools::Datasections


=head1 DESCRIPTION

Data::Load::Datasection  - Load and keep data sections from named *.pm



=head1 REQUIRES

L<Daje::Generate::Templates::Perl> 

L<Daje::Generate::Templates::Sql> 

L<Mojo::Loader> 

L<feature> 

L<v5.40> 


=head1 METHODS

Get one section of loaded data
my $c1 = $data->get_data_section('c1');
Add a section of data
$data->set_data_section('new_section', 'section data');
Set a new source
$data->set_source('New::Source');
Add a new section to load
$data->add_data_section('test');




=head1 Synopsis


use GenerateSQL::Tools::Datasections

my $data = GenerateSQL::Tools::Datasections->new(
      data_sections => ['c1','c2','c3'],
      source => 'Class::Containing::Datasections
  )->load_data_sections();



=head1 AUTHOR

Jan Eskilsson



=head1 COPYRIGHT

Copyright (C) 2024 Jan Eskilsson.



=head1 LICENSE

Generate::Tools::Datasections  (the distribution) is licensed under the same terms as Perl.



=cut

